name: doldur_kabi
description: "Sokak hayvanları besleme takip uygulaması"

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  il_ilce: ^1.0.0
  intl: ^0.20.2
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web:
  google_maps_flutter_ios:
  google_maps_flutter_android: ^2.8.0
  cupertino_icons:
  url_launcher: ^6.3.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  google_sign_in: ^6.2.2
  google_fonts: ^5.0.0
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  custom_info_window: ^1.0.1
  path_provider: ^2.1.5
  firebase_messaging: ^15.2.4
  flutter_native_splash:
  image: ^4.0.17
  share_plus: ^10.1.4
  font_awesome_flutter: ^10.7.0
  flutter_local_notifications: ^18.0.1
  dropdown_button2: ^2.3.9
  lottie: ^2.6.0
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.1.0
  transparent_image: ^2.0.0
  image_cropper: ^5.0.1
  introduction_screen: ^3.1.7
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  screenshot: ^1.3.0
  permission_handler: ^11.0.1
  pdf: ^3.10.4
  printing: ^5.12.0
  photo_manager: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.0

flutter_native_splash:
  color: "#9346A1"
  image: assets/images/splash2.png
  fullscreen: true
  android_12:
    color: "#9346A1"
    image: assets/images/splash2.png
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
