// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQKRgrjfCYBi5pXP9jt0mcqLTYCsrDs4o',
    appId: '1:618741724404:web:04c3b37bedb45605e5daa1',
    messagingSenderId: '618741724404',
    projectId: 'doldur-kabi-48e54',
    authDomain: 'doldur-kabi-48e54.firebaseapp.com',
    storageBucket: 'doldur-kabi-48e54.firebasestorage.app',
    measurementId: 'G-GZEFLHKS7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT7OlAJbQV8AYIMgxvsXoWp4FbhtT9qBk',
    appId: '1:618741724404:android:8d00a77a5bfe551ee5daa1',
    messagingSenderId: '618741724404',
    projectId: 'doldur-kabi-48e54',
    storageBucket: 'doldur-kabi-48e54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARW_KKFYqkoBn0m99us49eQAnspRXl9lo',
    appId: '1:618741724404:ios:6a975f98ece15255e5daa1',
    messagingSenderId: '618741724404',
    projectId: 'doldur-kabi-48e54',
    storageBucket: 'doldur-kabi-48e54.firebasestorage.app',
    androidClientId: '618741724404-o4l17m39grak5tt92bv1qt9cv7d9b80b.apps.googleusercontent.com',
    iosClientId: '618741724404-ruuq2oogt4lgmb7ie46giqtinc4d5nch.apps.googleusercontent.com',
    iosBundleId: 'com.example.doldurKabi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARW_KKFYqkoBn0m99us49eQAnspRXl9lo',
    appId: '1:618741724404:ios:6a975f98ece15255e5daa1',
    messagingSenderId: '618741724404',
    projectId: 'doldur-kabi-48e54',
    storageBucket: 'doldur-kabi-48e54.firebasestorage.app',
    androidClientId: '618741724404-o4l17m39grak5tt92bv1qt9cv7d9b80b.apps.googleusercontent.com',
    iosClientId: '618741724404-ruuq2oogt4lgmb7ie46giqtinc4d5nch.apps.googleusercontent.com',
    iosBundleId: 'com.example.doldurKabi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQKRgrjfCYBi5pXP9jt0mcqLTYCsrDs4o',
    appId: '1:618741724404:web:ad8861811ad0b732e5daa1',
    messagingSenderId: '618741724404',
    projectId: 'doldur-kabi-48e54',
    authDomain: 'doldur-kabi-48e54.firebaseapp.com',
    storageBucket: 'doldur-kabi-48e54.firebasestorage.app',
    measurementId: 'G-MM6B99Q1XW',
  );

}